# .github/workflows/auto-pr.yml
name: Auto PR

on:
  push:
    branches-ignore:
      - main  # Ignora pushes directos a 'main'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Crear Pull Request automático
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto PR desde ${{ github.ref_name }}"
          title: "Auto PR desde ${{ github.ref_name }}"
          body: |
            Pull Request generado automáticamente desde la rama `${{ github.ref_name }}`
          base: main
          branch: ${{ github.ref_name }}
          draft: false
